name: Deploy to Heroku
on: [push]
jobs:
  push-to-heroku:
    runs-on: ubuntu-latest
    env: 
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - run: heroku git:remote -a cryptic-badlands-5383
      - run: git push heroku master
