name: Deploy to Heroku
on: [push]
jobs:
  push-to-heroku:
    runs-on: ubuntu-latest
    steps:
      - env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          MY_SECRET: ${{ secrets.MY_SECRET }}
      - run: echo $MY_SECRET
      - run: heroku git:remote -a cryptic-badlands-5383
      - run: git push heroku master
