name: Deploy to Heroku
on: [push]
jobs:
  push-to-heroku:
    runs-on: ubuntu-latest
    env: 
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - run: git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/cryptic-badlands-5383.git
      - run: git push heroku master
